### ISSUE TITLE
Warning: Range var backend copies lock

### ISSUE THREAD

**Issue by wolflegend99** [bmf-san/godon#2]
Hi @bmf-san 
I am getting some warnings in the code which point to line 93 @ server.go:
```golang 
    for _, backend := range cfg.Backends {
```
The warning spew points to the Backend struct:

```golang
type Backend struct {
	URL    string `json:"url"`
	IsDead bool
	mu     sync.RWMutex
}
```

**Fix: The sync.RWMutex variable should be embedded into a pointer.** 
```golang
	mu     *sync.RWMutex

```
Since we are assigning a temp var as backend, which holds the object of the used in the loop. The issue arises here, since we are holding a value of the mutex, and not the actual reference to the Mutex. Granted, we don't use the Mutex anywhere in the range in the healthcheck function, so we don't run into problems.

Feel free to correct me, if I am wrong 🙂

**Comment by bmf-san** [comment]
@wolflegend99 
Sorry for the late reply😓 
As you pointed out, I fixed it. https://github.com/bmf-san/godon/pull/3#pullrequestreview-1072590013
Thanks :D
