### ISSUE TITLE
Source code - runtime error

### ISSUE THREAD

**Issue by blockchain-app12** [bmf-san/godon#4]
Hi,
I follow the instructions as per given in the website and also clone these github repo. when I try to run the main file after the build, it shows error as like run time error.
I hereby attached the error as below.
kindly let me know to resolve this issue !

![go_reverseproxy_issue](https://user-images.githubusercontent.com/48212011/193753982-ba433ffc-138b-4b96-825b-de30ea14a1d8.png)

**Comment by bmf-san** [comment]
@blockchain-app12 
Sorry for replying late. I fixed it.

https://github.com/bmf-san/godon/pull/5
